/* Auto-generated by scripts/release.sh - do not edit manually */
#ifndef TELNET_LISP_VERSION_H
#define TELNET_LISP_VERSION_H

#define TELNET_LISP_BASE_VERSION "0.4"
#define TELNET_LISP_VERSION_MAJOR 0
#define TELNET_LISP_VERSION_MINOR 4

#endif /* TELNET_LISP_VERSION_H */
