#!/bin/bash
# Create a release with GitHub integration
#
# Usage: ./scripts/release.sh MAJOR.MINOR [--draft]
# Example: ./scripts/release.sh 0.4
#         ./scripts/release.sh 0.4 --draft
#
# This script:
# 1. Validates the version format (MAJOR.MINOR)
# 2. Checks the working directory is clean
# 3. Checks gh CLI is available and authenticated
# 4. Checks the tag doesn't already exist (local and remote)
# 5. Updates src/version.h and telnet-lisp/src/version.h
# 6. Commits the version updates
# 7. Creates an annotated tag vMAJOR.MINOR
# 8. Pushes commit and tag to origin
# 9. Creates a GitHub release with auto-generated notes

set -e

# Parse arguments
VERSION=""
DRAFT=""

while [ $# -gt 0 ]; do
  case "$1" in
  --draft)
    DRAFT="--draft"
    shift
    ;;
  -h | --help)
    echo "Create a GitHub release"
    echo ""
    echo "Usage: $0 MAJOR.MINOR [--draft]"
    echo ""
    echo "Arguments:"
    echo "  MAJOR.MINOR    Version number (e.g., 0.4)"
    echo ""
    echo "Options:"
    echo "  --draft        Create as draft release (not published)"
    echo "  -h, --help     Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 0.4           # Create and publish release v0.4"
    echo "  $0 0.4 --draft   # Create draft release v0.4"
    exit 0
    ;;
  *)
    if [ -z "$VERSION" ]; then
      VERSION="$1"
    else
      echo "Error: Unexpected argument: $1"
      exit 1
    fi
    shift
    ;;
  esac
done

# Check version was provided
if [ -z "$VERSION" ]; then
  echo "Error: Version not specified"
  echo ""
  echo "Usage: $0 MAJOR.MINOR [--draft]"
  echo "Example: $0 0.4"
  exit 1
fi

TAG_NAME="v$VERSION"

# Parse MAJOR and MINOR from version
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)

# Validate version format (MAJOR.MINOR)
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+$'; then
  echo "Error: Invalid version format: $VERSION"
  echo "Expected format: MAJOR.MINOR (e.g., 0.4)"
  exit 1
fi

# Check gh CLI is available
if ! command -v gh &>/dev/null; then
  echo "Error: GitHub CLI (gh) is not installed"
  echo ""
  echo "Install it from: https://cli.github.com/"
  echo "  Windows (scoop): scoop install gh"
  echo "  macOS (brew): brew install gh"
  echo "  Linux: see https://github.com/cli/cli/blob/trunk/docs/install_linux.md"
  exit 1
fi

# Check gh is authenticated
if ! gh auth status &>/dev/null; then
  echo "Error: GitHub CLI is not authenticated"
  echo ""
  echo "Run: gh auth login"
  exit 1
fi

# Check working directory is clean
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Working directory is not clean!"
  echo "Please commit or stash your changes before creating a release."
  echo ""
  echo "Uncommitted changes:"
  git status --porcelain
  exit 1
fi

# Check tag doesn't already exist locally
if git tag -l "$TAG_NAME" | grep -q "$TAG_NAME"; then
  echo "Error: Tag $TAG_NAME already exists locally!"
  exit 1
fi

# Check tag doesn't already exist on remote
if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
  echo "Error: Tag $TAG_NAME already exists on remote!"
  exit 1
fi

echo "Creating release $TAG_NAME..."
echo ""

# Update version.h files
update_version_header() {
  local file="$1"
  local prefix="$2"

  cat >"$file" <<EOF
/* Auto-generated by scripts/release.sh - do not edit manually */
#ifndef ${prefix}_VERSION_H
#define ${prefix}_VERSION_H

#define ${prefix}_BASE_VERSION "$VERSION"
#define ${prefix}_VERSION_MAJOR $MAJOR
#define ${prefix}_VERSION_MINOR $MINOR

#endif /* ${prefix}_VERSION_H */
EOF
  echo "Updated: $file"
}

echo "Updating version headers..."
update_version_header "src/version.h" "TELNET_GUI"
update_version_header "telnet-lisp/src/version.h" "TELNET_LISP"
echo ""

# Commit version updates
echo "Committing version updates..."
git add src/version.h telnet-lisp/src/version.h
git commit -m "Release $VERSION"
echo ""

# Create annotated tag on the new commit
echo "Creating annotated tag: $TAG_NAME"
git tag -a "$TAG_NAME" -m "Release $VERSION"
echo ""

# Push commit and tag
echo "Pushing to origin..."
git push origin HEAD
git push origin "$TAG_NAME"
echo ""

# Create GitHub release
echo "Creating GitHub release..."
if [ -n "$DRAFT" ]; then
  echo "(Creating as draft release)"
fi

gh release create "$TAG_NAME" \
  --title "Release $VERSION" \
  --generate-notes \
  $DRAFT

echo ""
echo "========================================"
echo "Release $TAG_NAME created successfully!"
echo "========================================"
echo ""

# Show release URL
RELEASE_URL=$(gh release view "$TAG_NAME" --json url -q .url)
echo "Release URL: $RELEASE_URL"
echo ""

if [ -n "$DRAFT" ]; then
  echo "Note: This is a draft release. Visit the URL above to publish it."
fi
