#!/bin/bash
# Create a release tag with optional GitHub release
#
# Usage: ./scripts/release.sh MAJOR.MINOR [OPTIONS]
# Example: ./scripts/release.sh 0.4
#         ./scripts/release.sh 0.4 --github owner/repo
#         ./scripts/release.sh 0.4 --github owner/repo --draft
#
# This script:
# 1. Validates the version format (MAJOR.MINOR)
# 2. Checks the working directory is clean
# 3. Checks the tag doesn't already exist (local and remote)
# 4. Updates src/version.h and telnet-lisp/src/version.h
# 5. Commits the version updates
# 6. Creates an annotated tag vMAJOR.MINOR
# 7. Pushes commit and tag to origin
# 8. (Optional) Creates a GitHub release if --github is specified

set -e

# Parse arguments
VERSION=""
DRAFT=""
GITHUB_REPO=""

while [ $# -gt 0 ]; do
  case "$1" in
  --draft)
    DRAFT="--draft"
    shift
    ;;
  --github)
    if [ -z "$2" ] || [[ "$2" == --* ]]; then
      echo "Error: --github requires a repository argument (owner/repo)"
      exit 1
    fi
    GITHUB_REPO="$2"
    shift 2
    ;;
  -h | --help)
    echo "Create a release tag with optional GitHub release"
    echo ""
    echo "Usage: $0 MAJOR.MINOR [OPTIONS]"
    echo ""
    echo "Arguments:"
    echo "  MAJOR.MINOR              Version number (e.g., 0.4)"
    echo ""
    echo "Options:"
    echo "  --github OWNER/REPO      Create GitHub release (requires gh CLI)"
    echo "  --draft                  Create as draft release (with --github)"
    echo "  -h, --help               Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 0.4                              # Tag only, no GitHub release"
    echo "  $0 0.4 --github louisbloom/telnet-gui    # With GitHub release"
    echo "  $0 0.4 --github louisbloom/telnet-gui --draft  # Draft release"
    exit 0
    ;;
  *)
    if [ -z "$VERSION" ]; then
      VERSION="$1"
    else
      echo "Error: Unexpected argument: $1"
      exit 1
    fi
    shift
    ;;
  esac
done

# Check version was provided
if [ -z "$VERSION" ]; then
  echo "Error: Version not specified"
  echo ""
  echo "Usage: $0 MAJOR.MINOR [--github OWNER/REPO] [--draft]"
  echo "Example: $0 0.4"
  exit 1
fi

TAG_NAME="v$VERSION"

# Parse MAJOR and MINOR from version
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)

# Validate version format (MAJOR.MINOR)
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+$'; then
  echo "Error: Invalid version format: $VERSION"
  echo "Expected format: MAJOR.MINOR (e.g., 0.4)"
  exit 1
fi

# Check GitHub CLI if --github is specified
if [ -n "$GITHUB_REPO" ]; then
  if ! command -v gh &>/dev/null; then
    echo "Error: GitHub CLI (gh) is not installed"
    echo ""
    echo "Install it from: https://cli.github.com/"
    echo "  Windows (scoop): scoop install gh"
    echo "  macOS (brew): brew install gh"
    echo "  Linux: see https://github.com/cli/cli/blob/trunk/docs/install_linux.md"
    exit 1
  fi

  if ! gh auth status &>/dev/null; then
    echo "Error: GitHub CLI is not authenticated"
    echo ""
    echo "Run: gh auth login"
    exit 1
  fi
fi

# Warn if --draft used without --github
if [ -n "$DRAFT" ] && [ -z "$GITHUB_REPO" ]; then
  echo "Warning: --draft has no effect without --github"
fi

# Check working directory is clean
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Working directory is not clean!"
  echo "Please commit or stash your changes before creating a release."
  echo ""
  echo "Uncommitted changes:"
  git status --porcelain
  exit 1
fi

# Check tag doesn't already exist locally
if git tag -l "$TAG_NAME" | grep -q "$TAG_NAME"; then
  echo "Error: Tag $TAG_NAME already exists locally!"
  exit 1
fi

# Check tag doesn't already exist on remote
if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
  echo "Error: Tag $TAG_NAME already exists on remote!"
  exit 1
fi

echo "Creating release $TAG_NAME..."
echo ""

# Update version.h files
update_version_header() {
  local file="$1"
  local prefix="$2"

  cat >"$file" <<EOF
/* Auto-generated by scripts/release.sh - do not edit manually */
#ifndef ${prefix}_VERSION_H
#define ${prefix}_VERSION_H

#define ${prefix}_BASE_VERSION "$VERSION"
#define ${prefix}_VERSION_MAJOR $MAJOR
#define ${prefix}_VERSION_MINOR $MINOR

#endif /* ${prefix}_VERSION_H */
EOF
  echo "Updated: $file"
}

echo "Updating version headers..."
update_version_header "src/version.h" "TELNET_GUI"
update_version_header "telnet-lisp/src/version.h" "TELNET_LISP"
echo ""

# Commit version updates
echo "Committing version updates..."
git add src/version.h telnet-lisp/src/version.h
git commit -m "Release $VERSION"
echo ""

# Create annotated tag on the new commit
echo "Creating annotated tag: $TAG_NAME"
git tag -a "$TAG_NAME" -m "Release $VERSION"
echo ""

# Push commit and tag
echo "Pushing to origin..."
git push origin HEAD
git push origin "$TAG_NAME"
echo ""

echo "========================================"
echo "Release $TAG_NAME created successfully!"
echo "========================================"
echo ""

# Create GitHub release if requested
if [ -n "$GITHUB_REPO" ]; then
  echo "Creating GitHub release..."
  if [ -n "$DRAFT" ]; then
    echo "(Creating as draft release)"
  fi

  gh release create "$TAG_NAME" \
    --repo "$GITHUB_REPO" \
    --title "Release $VERSION" \
    --generate-notes \
    $DRAFT

  echo ""
  RELEASE_URL=$(gh release view "$TAG_NAME" --repo "$GITHUB_REPO" --json url -q .url)
  echo "GitHub release URL: $RELEASE_URL"
  echo ""

  if [ -n "$DRAFT" ]; then
    echo "Note: This is a draft release. Visit the URL above to publish it."
  fi
else
  echo "Tag pushed to origin. To create a GitHub release later:"
  echo "  gh release create $TAG_NAME --repo OWNER/REPO --generate-notes"
fi
